### ISSUE TITLE
Create a Search Bar that can search by Name, and Phone Number

### ISSUE THREAD

**Issue by aswinmohanme** [coronasafe/coronaRM#5]
The current user search form searches using id, and can be accessed by everyone. Create a new form in the admin dashboard page that can search through name, phone number, and flight details.

**Comment by nijeesh4all** [comment]
@aswinmohanme How do you want the search bar ? Should it be next to the current search box ?

**Comment by aswinmohanme** [comment]
I want it on the Admin Page, It should be above the Dashboard. 
It's fine if implemented as two search boxes, can you combine it into one ?

**Comment by aswinmohanme** [comment]
Also make it fuzzy, and should redirect to a page containing the results. If you don't want to do tailwind just include the basic HTML I'll add the stying
